public enum CustomerSpeechType
{
	THIS_IS_THEFT = 0,
	EXPENSIVE = 1,
	EXPENSIVE_FOR_ME = 2,
	CANT_FIND_ANYTHING = 3,
	CANT_FIND_SOMETHING = 4,
	CHANGE_PRICE_WHILE_SHOPPING = 5,
	FULL_CHECKOUTS = 6,
	FULL_RACKS = 7,
	NEED_HELP = 8,
	DIRTY_STORE = 9,
	BEAT_CUSTOMER = 10,
	CRATE_FULL = 11,
	MISSING_SCALE = 12,
	SCALE_LINE_TOO_LONG = 13,
	ITS_NOT_DISCOUNTED = 14,
	BAKER_NO_DISPLAY = 15,
	BAKER_NO_RACK = 16,
	INCORRECT_ICECREAM = 17,
	NO_ENOUGH_FLAVOUR = 18,
	MISSING_CONE = 19
}
