using System;

[Serializable]
public enum DisplaySubType
{
	None = 0,
	SHELF_STANDART = 1,
	SHELF_SINGLE = 2,
	SHELF_QUAD = 3,
	SHELF_QUADHALF = 4,
	SHELF_HALF = 5,
	SHELF_OUTER = 6,
	SHELF_INNER = 7,
	FREEZER_DOUBLE = 8,
	FREEZER_SINGLE = 9,
	FREEZER_TRIPLE = 10,
	FRIDGE_DOUBLE = 11,
	FRIDGE_MINI = 12,
	FRIDGE_SINGLE = 13,
	FRIDGE_DISPLAYFRIDGE_SINGLE = 14,
	FRIDGE_DISPLAYFRIDGE_DOUBLE = 15,
	SMALL_RACK = 16,
	TALL_RACK = 17,
	STALL_DEFAULT = 18,
	OVEN_DEFAULT = 19,
	VENDING_MACHINE = 20
}
