public enum ExpenseType
{
	INDOOR_LIGHT = 0,
	SMALL_FRIDGE = 1,
	LARGE_FRIDGE = 2,
	SMALL_FREEZER = 3,
	MEDIUM_FREEZER = 4,
	LARGE_FREEZER = 5,
	CHECKOUT = 6,
	SELF_CHECKOUT = 7,
	SPEAKER = 8,
	SECURITY = 9,
	OVEN = 10
}
